services:
  db:
    image: postgres:16-alpine
    container_name: go_react_app_db
    platform: linux/amd64
    ports:
      - "5434:5432"
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: go_react_app
    restart: always
    networks:
      - go_react_app_network
  api:
    build: 
      context: ./docker/api
      dockerfile: Dockerfile
    container_name: go_react_app_api
    platform: linux/amd64
    ports:
      - "8000:8000"
    volumes:
      - ./api:/go/src/api
      - ./docker/api/env/dev/.env:/go/src/api/.env
    depends_on:
      - db
    restart: always
    environment:
      - TZ=Asia/Tokyo
      - GO_ENV=dev
      - SMTP_HOST=mail
      - SMTP_PORT=1025
    tty: true
    command: air .air.toml
    networks:
      - go_react_app_network
  web:
    build:
      context: ./docker/web
      dockerfile: Dockerfile
    container_name: go_react_app_web
    platform: linux/amd64
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
    depends_on:
      - api
    restart: always
    environment:
      - TZ=Asia/Tokyo
    tty: true
    command: npm start
    networks:
      - go_react_app_network
  mail:
    image: mailhog/mailhog:latest
    platform: linux/amd64
    restart: always
    environment:
      - TZ=Asia/Tokyo
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - go_react_app_network
networks:
  go_react_app_network:
    external: true