version: "3.8"
services:
  dev-postgres:
    image: postgres:16-alpine
    ports:
      - "5434:5432"
    environment: 
      POSTGRES_USER: udemy
      POSTGRES_PASSWORD: udemy
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: udemy
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 82:80
    environment:
      PGADMIN_DEFAULT_EMAIL: udemy@example.com
      PGADMIN_DEFAULT_PASSWORD: udemypassword
    volumes:
      - ./docker/pgadmin:/var/lib/pgadmin
    depends_on:
      - dev-postgres
