services:
  db:
    image: postgres:16-alpine
    container_name: go_react_app_db
    ports:
      - "5434:5432"
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: go_react_app
    restart: always
  api:
    build: 
      context: ./docker/api
      dockerfile: Dockerfile
    container_name: go_react_app_api
    ports:
      - "8000:8000"
      - "2345:2345"
    volumes:
      - ./api:/go/src/api
      - ./docker/api/env/dev/.env:/go/src/api/.env
    depends_on:
      - db
    environment:
      - TZ=Asia/Tokyo
      - GO_ENV=dev
#    networks:
#      - go_react_app_network
    security_opt:
      - "apparmor=unconfined"
    cap_add:
      - SYS_PTRACE
  web:
    build:
      context: ./docker/web
      dockerfile: Dockerfile
    container_name: go_react_app_web
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
    depends_on:
      - api
    environment:
      - TZ=Asia/Tokyo
    tty: true
    command: npm start
  mail:
    image: mailhog/mailhog:latest
    container_name: go_react_app_mail
    restart: always
    environment:
      - TZ=Asia/Tokyo
    ports:
      - "8025:8025"
      - "1025:1025"
#  job:
#    build:
#      context: ./docker/job
#      dockerfile: Dockerfile
#    container_name: go_react_app_job
#    ports:
#      - "3001:3001"
#    volumes:
#      - ./job:/usr/src/app
#    environment:
#      - TZ=Asia/Tokyo
#    tty: true